const OPEN_CONGRATULATION = 'OPEN_CONGRATULATION';
const CLOSE_CONGRATULATION = 'CLOSE_CONGRATULATION ';
const OPEN_ERROR_MODAL = 'OPEN_ERROR_MODAL ';
const CLOSE_ERROR_MODAL = 'CLOSE_ERROR_MODAL  ';

export default {
  CLOSE_CONGRATULATION,
  OPEN_CONGRATULATION,
  OPEN_ERROR_MODAL,
  CLOSE_ERROR_MODAL,
};
